.
Fixed 'AttributeError: 'NoneType' object has no attribute 'mention']'

It was occurring due to anonymous admin use /start command, from now if anonymous admin use /start command it won't mention them.