Fixed `AttributeError: 'list' object has no attribute 'strip'`
The error occurring due to the code trying to call the strip() method on a list object. So now i added str() func to ensure that it is a string not a list object.