.
Fixed ```AttributeError: 'NoneType' object has no attribute 'id'```

This was occuring due to anonymous admin was searching so from_user was returning None.